Rails.application.routes.draw do
  get 'ideas/new'
  get 'ideas/show'
  get 'pages/show'
  get 'pages/approved_idea'
  get 'themes/new'
  get 'themes/show'
  get 'themes/index'
  get 'solutions/index'
  get 'solutions/show'
  get 'solutions/approved_solution'
  get 'categories/new'
  resources :solutions
  resources :themes
  resources :ideas
  resources :categories
  devise_for :users
get 'pages/new_idea'
get 'pages/view_ap_idea'
get 'pages/view_ap_theme'
get 'pages/index_student'
get 'pages/post_solution'
get 'pages/edit_idea'
get 'pages/index_tcser'
get 'pages/review_idea'
get 'pages/review_theme'
get 'pages/post_theme'
root 'pages#index_student'
end
